# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/Mapxus/mapxusSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'UICoreSDKKmpExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UICoreSDKKmpExample
  
  pod 'DropInUISDK', :path => '../integration-dropin-ui-sdk-ios'

  target 'UICoreSDKKmpExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UICoreSDKKmpExampleUITests' do
    # Pods for testing
  end

end


#if [ "YES" = "$OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED" ]; then
