# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#


# 指定项目的scheme名称
scheme = "UISDKKmpSample"
icon_path = './UISDKKmpSample/Assets.xcassets/AppIcon.appiconset/1024.png'
ipa_dir = "./fastlane_build"
ipa_name = "#{scheme}.ipa"

default_platform(:ios)

def ensure_local_secrets_config!
  secrets_path = File.expand_path("../BuildConfig/Secrets.local.xcconfig", __dir__)
  return if File.exist?(secrets_path)

  UI.user_error!("Missing BuildConfig/Secrets.local.xcconfig. Copy BuildConfig/Secrets.example.xcconfig to BuildConfig/Secrets.local.xcconfig and fill in MAPXUS_API_KEY and MAPXUS_SECRET before running fastlane.")
end

platform :ios do

  #######################################################################################################################################
  #######################################################################################################################################
  #######################################################################################################################################

  before_all do |lane|
    ensure_local_secrets_config!

    # 清理编译文件
    clear_derived_data

    # 安装第三方库
    cocoapods(use_bundle_exec: true, repo_update: true)

  end

  #######################################################################################################################################
  #######################################################################################################################################
  #######################################################################################################################################

  desc "Upload the package to fir.im"
  lane :fir do

    bundle_id = "com.mapxus.uisdk-showcase.ios"

    # development证书也要一起请求，否则Xcode的自动签名功能会自动生成开发证书，导致证书过多
    match(type: "development", app_identifier: bundle_id)
    match(type: "adhoc", app_identifier: bundle_id)

    # gym用来编译 打包 签名
    gym(
      output_directory: ipa_dir,
      output_name: ipa_name,
      clean: true,
      workspace: scheme + ".xcworkspace",
      scheme: scheme,
      export_method: 'ad-hoc',
      xcargs: "-allowProvisioningUpdates"
    )

    change_log = changelog_from_git_commits(merge_commit_filtering: "exclude_merges")

    # upload app
    fir_cli(
      specify_file_path: "#{ipa_dir}/#{ipa_name}",
      skip_update_icon: false,
      specify_icon_file: icon_path,
      api_token: ENV['fir_api_token'],  
      changelog: change_log
    )

  end
end
